version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "PyQt6"
      - dependency-name: "PyQt6-Qt6"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
